import { NextRequest, NextResponse } from 'next/server';
import OpenAI from 'openai';

// Default prompt for email generation
const DEFAULT_EMAIL_PROMPT = `
  You are a friendly, relatable email writer who writes like an average Indian professional using simple, layman Indian English. Generate an email for a job application based on the provided job description. The email must:
  - Include only skills, qualifications, and details relevant to the job description.
  - Be short, simple, and written in a casual yet professional tone, like how a regular Indian person would write.
  - Sound 100% human, unique, and natural, with slight imperfections (e.g., small typos, casual phrasing, or Indian English quirks).
  - Avoid perfect, polished AI-like language; make it feel like a real person typed it 100%.
  - Include standard email components (e.g., subject line, greeting, body, closing) in plain text.
  - Reflect Indian cultural nuances, like humility and respect, while keeping it professional but not overly formal.
  - make sure it is written by a human and not an AI. very important.
`;

export async function GET() {
  // Return the default prompt
  return NextResponse.json({
    emailPrompt: DEFAULT_EMAIL_PROMPT,
  });
}

export async function POST(request: NextRequest) {
  console.log('Received POST request to /api/generate-mail');
  try {
    // Get API key from headers or environment
    const apiKey =
      request.headers.get('X-OpenAI-Api-Key') || process.env.KEY_4_OPENAI;
    if (!apiKey) {
      console.error('No OpenAI API key provided');
      return NextResponse.json(
        { error: 'No OpenAI API key provided. Please set it in Settings.' },
        { status: 500 }
      );
    }

    const openai = new OpenAI({ apiKey });

    // Parse JSON body
    console.log('Parsing request body');
    const { jobDescription, customEmailPrompt } = await request.json();
    console.log('Request body parsed', {
      hasJobDescription: !!jobDescription,
      jobDescriptionLength: jobDescription?.length,
      hasCustomPrompt: !!customEmailPrompt,
    });

    if (
      !jobDescription ||
      typeof jobDescription !== 'string' ||
      !jobDescription.trim()
    ) {
      console.log('Missing or invalid job description');
      return NextResponse.json(
        { error: 'Please provide a valid job description' },
        { status: 400 }
      );
    }

    // Generate email with Open AI
    console.log('Generating email with Open AI');
    try {
      const prompt = `
        ${customEmailPrompt || DEFAULT_EMAIL_PROMPT}
        
        Job Description:
        ${jobDescription}
        
        Output the email in plain text, starting with the subject line:
      `;

      const completion = await openai.chat.completions.create({
        model: 'gpt-4o',
        messages: [
          { role: 'system', content: 'You are a professional email writer.' },
          { role: 'user', content: prompt },
        ],
        max_tokens: 500,
      });

      const content = completion.choices[0]?.message.content || '';
      console.log('Email generated', { contentLength: content.length });

      if (!content) {
        console.log('No content generated by Open AI');
        return NextResponse.json(
          { error: 'Failed to generate email: No content returned' },
          { status: 500 }
        );
      }

      console.log('Returning generated email');
      return NextResponse.json({ content });
    } catch (error) {
      console.error('Error generating email:', error);
      return NextResponse.json(
        {
          error:
            error instanceof Error ? error.message : 'Failed to generate email',
        },
        { status: 500 }
      );
    }
  } catch (error) {
    console.error('Error processing request:', error);
    return NextResponse.json(
      {
        error:
          error instanceof Error ? error.message : 'Failed to process request',
      },
      { status: 500 }
    );
  }
}
